# 使用 OpenAPI 3.0.3 標準

openapi: 3.0.3



# --- API 基本資訊 ---

# 提供 API 的整體描述、標題和版本號

info:

  title: MindTrack API

  description: >-

    一個旨在幫助使用者追蹤好習慣、記錄每日心情，並透過視覺化洞察揭示行為與感受之間關聯的 Web

    應用程式。我們的願景是打造一個最直覺、最富有洞察力的個人成長工具。    

  version: 1.0.0



# --- 伺服器資訊 ---

# 定義 API 的不同環境，例如開發和生產環境

servers:

  - url: http://localhost:5000/api/v1

    description: 本地開發伺服器



# --- API 路由 (Endpoints) ---

# 這裡是 API 功能的核心，定義了所有可用的 URL 路徑和對應的 HTTP 方法

paths:

  # --- 使用者認證 (Authentication) ---

  /auth/register:

    post:

      tags:

        - Authentication

      summary: 註冊新使用者

      requestBody:

        required: true

        content:

          application/json:

            schema:

              $ref: '#/components/schemas/UserCredentials'

      responses:

        '201':

          description: 使用者成功建立

          ...

        '400':

          $ref: '#/components/responses/ValidationError'



  /auth/login:

    post:

      tags:

        - Authentication

      summary: 使用者登入

      ...



  # --- 習慣 (Habits) 管理 ---

  /habits:

    get:

      tags:

        - Habits

      summary: 獲取當前使用者的所有習慣

      security:

        - BearerAuth: []

      parameters:

        - $ref: '#/components/parameters/QueryLimit'

        - $ref: '#/components/parameters/QueryOffset'

      responses:

        '200':

          description: 成功返回習慣列表

          ...

    post:

      tags:

        - Habits

      summary: 建立一個新習慣

      ...



  /habits/{habitId}:

    parameters:

      - name: habitId

        in: path

        required: true

        ...

    get:

      summary: 根據 ID 獲取特定習慣

      ...

    put:

      summary: 根據 ID 更新特定習慣

      ...

    delete:

      summary: 根據 ID 刪除特定習慣

      ...



  # --- 習慣與心情紀錄 ---

  /habit-logs:

    post:

      summary: 為指定習慣新增一筆完成紀錄 (打卡)

      ...



  /mood-logs:

    post:

      summary: 新增或更新當日的心情紀錄

      ...



# --- 可重用元件 (Components) ---

# 定義可以在 API 各處重複使用的元素，例如資料模型、參數和安全機制

components:

  # 安全性方案：定義如何進行身份驗證，這裡是使用 JWT Bearer Token

  securitySchemes:

    BearerAuth:

      type: http

      scheme: bearer

      bearerFormat: JWT



  # 可重用參數：例如用於分頁的 limit 和 offset

  parameters:

    QueryLimit:

      name: limit

      in: query

      ...

    QueryOffset:

      name: offset

      in: query

      ...



  # 可重用回應：定義通用的 API 回應，如 401 未授權、404 找不到等

  responses:

    UnauthorizedError:

      description: 認證失敗或缺少憑證

      ...

    NotFoundError:

      description: 找不到指定的資源

      ...

    ValidationError:

      description: 請求的資料格式無效

      ...



  # 資料模型 (Schemas)：定義 API 中使用的資料結構

  schemas:

    UserCredentials:

      type: object

      properties:

        email:

          type: string

          format: email

        password:

          type: string

          format: password



    User:

      type: object

      properties:

        id:

          type: integer

        email:

          type: string

        ...



    Habit:

      type: object

      properties:

        id:

          type: integer

        name:

          type: string

        ...



    HabitInput:

      ...

    HabitLog:

      ...

    HabitLogInput:

      ...

    MoodLog:

      ...

    MoodLogInput:

      ...



    Error:

      type: object

      properties:

        code:

          type: string

        message:

          type: string
